name: weatherapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  dartz:
  equatable:
  internet_connection_checker:
  shared_preferences:
  http:
  get_it:
  flutter_glow: ^0.3.0
  flutter_spinkit: ^5.2.0
  fl_chart:
  syncfusion_flutter_charts:
  flutter_zoom_drawer: ^3.1.1
  percent_indicator: ^4.2.3
  geolocator:
  geocoding:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

